#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo
echo "Husky: POST-COMMIT hook started"
echo

command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but git-lfs was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.\n"; exit 2; }

git lfs post-commit "$@"

[ $? -eq 0 ] && echo "Husky: POST-COMMIT hook finished" && echo
