name: wagoid Lint Commit Messages

on: [push, pull_request]

env:
  ALL_COMMITS: 0

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.ALL_COMMITS }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      # Run the commitlint action, considering its own dependencies and yours as well 🚀
      - uses: wagoid/commitlint-github-action@v5
        env:
          # `github.workspace` is the path to your repository.
          NODE_PATH: ${{ github.workspace }}/node_modules
        with:
          configFile: '.commitlintrc'
      - name: Print Last commit message
        run: echo "${{ github.event.head_commit.message }}"
